-- ============================================================
-- Fitbud — datos precargados (ejecuta DESPUÉS de schema.sql)
-- Valores nutricionales por 100 g (aproximados, editables).
-- Base vegetariana + opciones omnívoras (carne/aves/pescado/huevo). Re-ejecutable: hace truncate primero.
-- ============================================================
truncate diet_dishes, diets, dish_ingredients, dishes, ingredients restart identity cascade;

-- ---------- INGREDIENTES (por 100 g) ----------
insert into ingredients (name, category, kcal, protein_g, carbs_g, fat_g) values
('Tofu firme','Proteína',145,16,3,9),
('Tempeh','Proteína',192,20,8,11),
('Seitán','Proteína',130,24,4,2),
('Proteína en polvo','Proteína',375,80,8,5),
('Caseína en polvo','Proteína',360,78,9,4),
('Soya texturizada (seca)','Proteína',330,52,14,3),
('Edamame','Proteína',121,12,9,5),
('Garbanzos cocidos','Legumbre',164,9,27,2.6),
('Lentejas cocidas','Legumbre',116,9,20,0.4),
('Frijoles negros cocidos','Legumbre',132,8.9,24,0.5),
('Frijoles canarios cocidos','Legumbre',120,8,22,0.5),
('Pallares cocidos','Legumbre',115,8,21,0.5),
('Hummus','Legumbre',166,8,14,10),
('Avena','Cereal',389,13,66,7),
('Arroz cocido','Cereal',130,2.7,28,0.3),
('Quinua cocida','Cereal',120,4.4,21,1.9),
('Pasta integral seca','Cereal',348,13,70,2.5),
('Fideos de arroz secos','Cereal',360,3.4,80,0.5),
('Fideos de trigo secos','Cereal',350,12,70,1.5),
('Tortilla de maíz','Cereal',218,5.7,45,2.9),
('Tortilla integral de trigo','Cereal',310,8,50,8),
('Pan pita integral','Cereal',275,9,55,1.2),
('Pan de molde','Cereal',265,9,49,3.2),
('Granola sin azúcar','Cereal',450,10,60,18),
('Yogur griego natural 0%','Lácteo',60,10,3.6,0.4),
('Queso cottage','Lácteo',98,11,3.4,4.3),
('Queso fresco','Lácteo',150,12,3,10),
('Parmesano','Lácteo',431,38,4,29),
('Leche vegetal','Lácteo',45,3,4,2),
('Leche de coco light','Lácteo',73,0.7,3,7),
('Leche evaporada light','Lácteo',100,7,10,3),
('Plátano','Fruta',89,1.1,23,0.3),
('Frutos rojos','Fruta',50,1,12,0.3),
('Frutos congelados','Fruta',55,0.7,13,0.3),
('Fruta pequeña (manzana)','Fruta',52,0.3,14,0.2),
('Palta','Grasa',160,2,9,15),
('Aceitunas','Grasa',115,0.8,6,11),
('Aceite de oliva','Grasa',884,0,0,100),
('Mantequilla de maní','Grasa',588,25,20,50),
('Maní','Grasa',567,26,16,49),
('Chía','Grasa',486,17,42,31),
('Brócoli','Verdura',34,2.8,7,0.4),
('Pak choi','Verdura',13,1.5,2,0.2),
('Champiñones','Verdura',22,3,3,0.3),
('Berenjena','Verdura',25,1,6,0.2),
('Pimiento','Verdura',31,1,6,0.3),
('Cebolla','Verdura',40,1.1,9,0.1),
('Tomate','Verdura',18,0.9,3.9,0.2),
('Zapallo','Verdura',26,1,6.5,0.1),
('Repollo','Verdura',25,1.3,6,0.1),
('Papa','Verdura',77,2,17,0.1),
('Verduras mixtas','Verdura',25,1.5,4,0.3),
('Alga nori','Verdura',35,6,5,0.3),
('Miel','Otros',304,0.3,82,0),
('Mermelada','Otros',250,0.5,65,0),
-- Proteínas animales (opciones omnívoras)
('Pechuga de pollo','Proteína animal',165,31,0,3.6),
('Pavo molido magro','Proteína animal',150,27,0,4),
('Carne de res magra','Proteína animal',137,21,0,5),
('Huevo entero','Proteína animal',143,13,1,9.5),
('Atún en agua','Proteína animal',116,26,0,1),
('Salmón','Proteína animal',208,20,0,13),
-- Lote 1 de crecimiento (REQ-135). Valores por 100 g aproximados desde tablas
-- nutricionales publicas/etiquetas; ver docs/catalog-lote-1-sources.md.
('Claras pasteurizadas','Proteína animal',52,11,0.7,0.2),
('Yogur de soya natural','Proteína vegetal',55,4,4,2),
('Proteina vegetal en polvo','Proteína',370,75,10,7),
('Tofu sedoso','Proteína',55,5,2,3),
('Leche de soya sin azucar','Proteína vegetal',33,3.3,0.7,1.8),
('Leche descremada','Lácteo',35,3.4,5,0.1),
('Skyr natural 0%','Lácteo',60,11,4,0.2),
('Ricotta light','Lácteo',138,11,5,7),
('Mozzarella light','Lácteo',190,24,3,10),
('Pechuga de pavo','Proteína animal',135,29,0,1),
('Jamon de pavo','Proteína animal',110,19,2,2),
('Camarones','Proteína animal',99,24,0.2,0.3),
('Merluza','Proteína animal',90,19,0,1.5),
('Tilapia','Proteína animal',96,20,0,2),
('Sardinas en agua','Proteína animal',130,25,0,5),
('Lomo de cerdo magro','Proteína animal',143,22,0,5),
('Pollo deshilachado','Proteína animal',165,31,0,3.6),
('Clara de huevo cocida','Proteína animal',52,11,0.7,0.2),
('Trucha','Proteína animal',148,20,0,6),
('Pan integral','Cereal',247,13,41,4.2),
('Wrap integral','Cereal',290,9,48,7),
('Arepa de maiz','Cereal',218,5,45,3),
('Galletas de arroz','Cereal',387,8,82,3),
('Cuscus cocido','Cereal',112,3.8,23,0.2),
('Bulgur cocido','Cereal',83,3.1,19,0.2),
('Cebada cocida','Cereal',123,2.3,28,0.4),
('Camote cocido','Cereal',86,1.6,20,0.1),
('Yuca cocida','Cereal',160,1.4,38,0.3),
('Maiz choclo','Cereal',96,3.4,21,1.5),
('Arroz integral cocido','Cereal',123,2.7,25.6,1),
('Pasta de legumbres seca','Cereal',350,24,56,2),
('Cereal integral sin azucar','Cereal',360,10,72,4),
('Arvejas cocidas','Legumbre',84,5.4,15,0.4),
('Lentejas rojas cocidas','Legumbre',116,9,20,0.4),
('Frijoles blancos cocidos','Legumbre',139,9.7,25,0.4),
('Habas cocidas','Legumbre',110,7.6,19,0.4),
('Garbanzos tostados','Legumbre',364,19,61,6),
('Fresa','Fruta',32,0.7,7.7,0.3),
('Arandanos','Fruta',57,0.7,14,0.3),
('Mango','Fruta',60,0.8,15,0.4),
('Pina','Fruta',50,0.5,13,0.1),
('Pera','Fruta',57,0.4,15,0.1),
('Naranja','Fruta',47,0.9,12,0.1),
('Datiles','Fruta',282,2.5,75,0.4),
('Pasas','Fruta',299,3.1,79,0.5),
('Espinaca','Verdura',23,2.9,3.6,0.4),
('Kale','Verdura',49,4.3,8.8,0.9),
('Pepino','Verdura',15,0.7,3.6,0.1),
('Zanahoria','Verdura',41,0.9,10,0.2),
('Zucchini','Verdura',17,1.2,3.1,0.3),
('Apio','Verdura',16,0.7,3,0.2),
('Esparragos','Verdura',20,2.2,3.9,0.1),
('Lechuga','Verdura',15,1.4,2.9,0.2),
('Almendras','Grasa',579,21,22,50),
('Nueces','Grasa',654,15,14,65),
('Tahini','Grasa',595,17,21,54),
('Semillas de calabaza','Grasa',559,30,11,49),
('Linaza molida','Grasa',534,18,29,42),
('Coco rallado','Grasa',660,7,24,65),
('Aceite de canola','Grasa',884,0,0,100),
-- Lote 2B de crecimiento (REQ-140). Valores por 100 g aproximados desde tablas
-- nutricionales publicas/etiquetas; ver docs/catalog-lote-2b-sources.md.
('Cancha serrana','Cereal',380,8,77,3),
('Ají amarillo','Verdura',50,2,10,1),
('Queso feta','Lácteo',264,14,4,21),
('Salsa de soya','Otros',53,8,5,0.1),
('Jengibre','Verdura',80,1.8,18,0.8),
('Ajonjolí','Grasa',573,18,23,50),
('Pasta de miso','Otros',200,12,26,6),
('Salsa teriyaki','Otros',89,6,16,0.1),
('Salsa de tomate natural','Otros',29,1.6,6,0.2),
('Pepinillos encurtidos','Verdura',11,0.3,2.3,0.2),
('Chile jalapeño','Verdura',29,0.9,6.5,0.4),
('Cilantro','Verdura',23,2.1,3.7,0.5),
('Limón','Fruta',29,1.1,9.3,0.3),
('Requesón','Lácteo',174,11,4,13),
('Lomo fino de res','Proteína animal',158,22,0,7.5),
('Bacalao desalado','Proteína animal',82,18,0,0.7),
('Pulpo cocido','Proteína animal',82,15,2.2,1),
('Huevo de codorniz','Proteína animal',158,13,0.4,11),
('Queso panela','Lácteo',262,18,2.3,20),
('Frijoles pintos cocidos','Legumbre',143,9,26,0.6),
('Frijoles rojos cocidos','Legumbre',127,8.7,22.8,0.5),
('Brotes de soya','Verdura',30,3,6,0.2),
('Setas shiitake','Verdura',34,2.2,6.8,0.5),
('Col morada','Verdura',31,1.4,7.4,0.2),
('Rábano','Verdura',16,0.7,3.4,0.1),
('Betarraga','Verdura',43,1.6,10,0.2),
('Coliflor','Verdura',25,1.9,5,0.3),
('Higos secos','Fruta',249,3.3,64,0.9),
('Ciruelas pasas','Fruta',240,2.2,64,0.4),
('Granada','Fruta',83,1.7,19,1.2),
('Kiwi','Fruta',61,1.1,15,0.5),
('Sandía','Fruta',30,0.6,7.6,0.2),
('Melón','Fruta',34,0.8,8.2,0.2),
('Aceite de sésamo','Grasa',884,0,0,100),
('Semillas de girasol','Grasa',584,21,20,51),
('Avellanas','Grasa',628,15,17,61),
('Leche entera','Lácteo',61,3.2,4.8,3.3),
('Pan integral de centeno','Cereal',259,8.5,48,3.3),
('Rúcula','Verdura',25,2.6,3.7,0.7),
('Puerro','Verdura',61,1.5,14,0.3),
('Nabo','Verdura',28,0.9,6.4,0.1),
-- Lote 2C de crecimiento (REQ-141). Valores por 100 g aproximados desde tablas
-- nutricionales publicas/etiquetas; ver docs/catalog-lote-2c-sources.md.
('Chuleta de cerdo','Proteína animal',209,27,0,10.5),
('Costilla de res','Proteína animal',291,20,0,23),
('Mejillones cocidos','Proteína animal',172,24,7.4,4.5),
('Calamar cocido','Proteína animal',92,15.6,3.1,1.4),
('Anchoas en aceite','Proteína animal',210,29,0,10),
('Jamón serrano','Proteína animal',241,32,1,13),
('Chorizo criollo','Proteína animal',455,24,3,38),
('Pollo molido','Proteína animal',143,17,0,8),
('Leche de almendra sin azúcar','Proteína vegetal',15,0.6,0.3,1.2),
('Bebida de coco sin azúcar','Proteína vegetal',24,0.2,3,1.8),
('Yogur de coco natural','Proteína vegetal',80,1,4,7),
('Yogur de almendra natural','Proteína vegetal',45,1,3,3.5),
('Queso vegano rallado','Grasa',280,3,10,25),
('Levadura nutricional','Otros',325,45,35,5),
('Harina de almendra','Grasa',571,21,20,50),
('Harina de arroz','Cereal',366,6,80,1.4),
('Harina de garbanzo','Cereal',387,22,58,6.7),
('Trigo sarraceno cocido','Cereal',92,3.4,20,0.6),
('Amaranto cocido','Cereal',102,3.8,19,1.6),
('Pan sin gluten multigrano','Cereal',250,6,50,3),
('Pasta de maíz cocida','Cereal',110,2,24,0.5),
('Alcachofa cocida','Verdura',47,3.3,10.5,0.2),
('Berros','Verdura',11,2.3,1.3,0.1),
('Hongos portobello','Verdura',22,2.1,3.9,0.4),
('Coles de Bruselas','Verdura',43,3.4,9,0.3),
('Tomatillo','Verdura',32,1,6,1),
('Nopal','Verdura',16,1.3,3.3,0.1),
('Chipotle en adobo','Verdura',32,1.3,7,0.5),
('Ají panca','Verdura',90,3,15,2),
('Rocoto','Verdura',40,1.5,9,0.3),
('Huacatay','Verdura',45,3,7,1),
('Aceitunas kalamata','Grasa',115,1,6,11),
('Semillas de cáñamo','Grasa',553,31,8.7,49),
('Crema agria light','Lácteo',130,3,5,11),
('Maracuyá','Fruta',97,2.2,23,0.7),
('Lúcuma','Fruta',99,1.5,25,0.5),
('Camu camu','Fruta',60,0.5,14,0.4),
('Papaya','Fruta',43,0.5,11,0.3);

-- ---------- PLATOS ----------
insert into dishes (name, slot, menu) values
-- Desayunos (compartidos)
('Avena proteica','desayuno',null),
('Bowl griego','desayuno',null),
('Panqueques sin huevo','desayuno',null),
('Smoothie bowl','desayuno',null),
('Desayuno refeed (avena + plátano + miel)','desayuno',null),
-- Batidos
('Batido peri-entreno (día pesas)','batido',null),
('Batido peri-entreno (día bajo)','batido',null),
-- Cenas (compartidas)
('Cena: yogur griego + cottage + fruta','cena',null),
('Cena: queso fresco a la plancha + palta','cena',null),
('Cena: crema de verduras + tofu sellado','cena',null),
('Cena exprés: caseína + mantequilla de maní','cena',null),
('Cena refeed: arroz + tofu + verduras','cena',null),
-- Snacks
('Snack refeed: pan + mermelada + proteína','snack',null),
('Snack diet break: pan con palta','snack',null),
('Snack extra: fruta + yogur','snack',null),
-- Shakes de proteína (REQ-76: opciones de alta proteína para tapar déficit)
('Shake de proteína con agua','snack',null),
('Shake de proteína con yogur griego','snack',null),
-- Menú A (Criollo)
('Saltado de tofu firme + arroz','almuerzo','A'),
('Lentejas guisadas + quinua + ensalada','almuerzo','A'),
('Tacu tacu de pallares + seitán','almuerzo','A'),
('Ají de garbanzos + arroz','almuerzo','A'),
('Quinua atamalada + queso fresco + tofu','almuerzo','A'),
('Frijoles canarios + arroz + queso fresco','almuerzo','A'),
('Locro de zapallo con quinua + tofu','almuerzo','A'),
-- Menú B (Mediterráneo)
('Pasta integral + boloñesa de lentejas + parmesano','almuerzo','B'),
('Bowl de hummus + tofu horneado + pita','almuerzo','B'),
('Falafel al horno + tabule de quinua + yogur','almuerzo','B'),
('Berenjenas al horno con lentejas + queso fresco','almuerzo','B'),
('Risotto de champiñones + tofu','almuerzo','B'),
('Ensalada griega + garbanzos + queso fresco','almuerzo','B'),
('Pisto de verduras + soya texturizada + papa','almuerzo','B'),
-- Menú C (Asiático)
('Tofu teriyaki + arroz + brócoli','almuerzo','C'),
('Curry de garbanzos + arroz','almuerzo','C'),
('Salteado de tempeh con pak choi y pimientos','almuerzo','C'),
('Pad thai de tofu','almuerzo','C'),
('Bowl de edamame + tofu + arroz + palta','almuerzo','C'),
('Ramen miso con tofu y fideos','almuerzo','C'),
('Chaufa de quinua con tofu','almuerzo','C'),
-- Menú D (Mexicano)
('Burrito bowl de frijol negro','almuerzo','D'),
('Chili vegetariano + arroz','almuerzo','D'),
('Tacos de frijol negro y queso fresco','almuerzo','D'),
('Fajitas de tofu + tortillas','almuerzo','D'),
('Quesadillas de frijol, queso y champiñones','almuerzo','D'),
('Enchiladas de frijol + cottage','almuerzo','D'),
('Sopa azteca + tofu + palta','almuerzo','D'),
-- Omnívoros (carne / aves / pescado / huevo)
('Huevos revueltos + avena','desayuno',null),
('Pollo a la plancha + arroz + brócoli','almuerzo',null),
('Bowl de atún + arroz + palta','almuerzo',null),
('Carne de res salteada + papa + verduras','cena',null),
('Salmón al horno + quinua + verduras','cena',null),
-- Lote 1 REQ-135: desayunos, snacks/batidos y cenas ligeras.
('Overnight de avena y skyr','desayuno',null),
('Tostadas de palta y huevo','desayuno',null),
('Wrap de claras y pavo','desayuno',null),
('Bowl tropical de yogur','desayuno',null),
('Avena mani y coco','desayuno',null),
('Arepa con queso fresco','desayuno',null),
('Smoothie verde proteico','desayuno',null),
('Pita de pollo y tomate','desayuno',null),
('Panqueques de avena con fresa','desayuno',null),
('Tostadas de ricotta y arandanos','desayuno',null),
('Bowl vegano de soya y granola','desayuno',null),
('Porridge de quinua y platano','desayuno',null),
('Huevos con camote','desayuno',null),
('Cereal integral con leche y fruta','desayuno',null),
('Yogur de soya con frutos rojos','snack',null),
('Garbanzos tostados con naranja','snack',null),
('Manzana con mantequilla de almendra','snack',null),
('Hummus con galletas de arroz','snack',null),
('Batido vegetal de platano','batido',null),
('Batido de skyr y mango','batido',null),
('Rollitos de pavo y pepino','snack',null),
('Cottage con pina','snack',null),
('Almendras y naranja','snack',null),
('Pita mini de hummus','snack',null),
('Smoothie de soya y fresa','batido',null),
('Caseina con arandanos','snack',null),
('Arepa mini con queso','snack',null),
('Sardinas con galletas de arroz','snack',null),
('Tofu sedoso con mango','snack',null),
('Edamame con choclo','snack',null),
('Wrap pequeno de pollo','snack',null),
('Datiles con mani','snack',null),
('Batido tropical vegetal','batido',null),
('Pera con nueces y skyr','snack',null),
('Bowl de pollo y camote','almuerzo',null),
('Ensalada de camarones y quinua','almuerzo',null),
('Merluza con arroz integral','almuerzo',null),
('Bowl vegano de lenteja roja y bulgur','almuerzo',null),
('Chili de frijol blanco y choclo','almuerzo',null),
('Wrap de tempeh y hummus','almuerzo',null),
('Pasta de legumbres con tomate y espinaca','almuerzo',null),
('Arepa de pavo y palta','almuerzo',null),
('Tilapia con zucchini y cuscus','cena',null),
('Trucha con camote y esparragos','cena',null),
('Ensalada de tofu sedoso y edamame','cena',null),
('Sopa de lenteja roja y verduras','cena',null),
('Pollo deshilachado con verduras','cena',null),
('Sardinas con ensalada y papa','cena',null),
('Cuscus con garbanzos y tahini','cena',null),
('Cerdo magro con yuca y repollo','cena',null),
-- Lote 2B REQ-140: profundidad por cocina (criolla/mediterranea/mexicana/asiatica)
-- en desayuno/snack/plato principal, mas escenarios low-budget/eat-out/alta
-- proteina sin depender de proteina en polvo. Fuentes en docs/catalog-lote-2b-sources.md.
('Tamal criollo de choclo y queso panela','desayuno',null),
('Sanguche criollo de pollo deshilachado','desayuno',null),
('Cancha criolla con queso fresco','snack',null),
('Camote criollo con queso panela','snack',null),
('Seco criollo de pollo con frijoles canarios','almuerzo',null),
('Cau cau criollo de pollo y papas','cena',null),
('Tostada mediterranea con hummus y tomate','desayuno',null),
('Pan pita con queso feta y aceitunas','desayuno',null),
('Hummus con bastones de pepino y zanahoria','snack',null),
('Mini pita con falafel','snack',null),
('Cuscus mediterraneo con garbanzos y aceitunas','almuerzo',null),
('Ensalada griega con pollo a la plancha','cena',null),
('Huevos rancheros estilo azteca','desayuno',null),
('Tacos de huevo y frijol','desayuno',null),
('Mini quesadilla de frijol y queso panela','snack',null),
('Nachos ligeros estilo azteca','snack',null),
('Fajitas de pollo con pimientos','almuerzo',null),
('Enchiladas de pollo con frijoles rojos','cena',null),
('Onigiri de edamame y atún','desayuno',null),
('Bowl de arroz y pak choi al vapor','desayuno',null),
('Edamame con sal marina','snack',null),
('Pepino con salsa teriyaki y ajonjolí','snack',null),
('Pad thai de camarones','almuerzo',null),
('Ramen de pollo, pak choi y miso','cena',null),
('Bowl de pollo, arroz y frijoles negros','almuerzo',null),
('Ensalada de atún con garbanzos y limón','almuerzo',null),
('Tacos de pollo con frijoles pintos','cena',null),
('Pasta integral con atún y tomate','cena',null),
('Bowl de huevo, camote y espinaca','almuerzo',null),
('Yogur griego con nueces y miel','snack',null),
('Requesón con higos y avellanas','snack',null),
('Bacalao al horno con papas y coliflor','cena',null),
('Pulpo a la parrilla con papas doradas','cena',null),
('Ensalada de lomo fino con rúcula y granada','almuerzo',null),
('Huevos de codorniz con palta y tostada','desayuno',null),
('Bowl de betarraga, garbanzos y queso feta','almuerzo',null),
('Salteado de setas shiitake y tofu','cena',null),
('Ensalada de col morada, rábano y pepinillos','snack',null),
('Batido de leche entera, plátano y avena','batido',null),
('Batido de sandía y limón','batido',null),
('Ensalada de melón y jamón de pavo','snack',null),
('Bowl de kiwi, yogur griego y semillas de girasol','desayuno',null),
('Sopa de puerro y papa','cena',null),
('Ensalada de nabo, zanahoria y pollo','almuerzo',null),
('Snack de ciruelas pasas y almendras','snack',null),
-- Lote 2C REQ-141: meta 180/200, gluten-free/dairy-free explicitos y mas
-- profundidad por cocina. Fuentes en docs/catalog-lote-2c-sources.md.
('Bowl de papaya y maracuyá con yogur de coco','desayuno',null),
('Panqueques de harina de almendra y arroz','desayuno',null),
('Porridge de trigo sarraceno y amaranto con frutos rojos','desayuno',null),
('Tostadas sin gluten con palta y huevo','desayuno',null),
('Bowl criollo de camote, huevo y ají amarillo','desayuno',null),
('Yogur de almendra con lúcuma y granola','desayuno',null),
('Pita con jamón serrano y tomate','desayuno',null),
('Tostadas mexicanas de tomatillo y huevo','desayuno',null),
('Bowl asiático de pollo molido, arroz y pak choi','almuerzo',null),
('Ensalada de mejillones con quinua y limón','almuerzo',null),
('Tacos de nopal y frijol negro','almuerzo',null),
('Chuleta de cerdo con puré de camote y coles de Bruselas','almuerzo',null),
('Seco criollo de costilla con frijoles canarios y ají panca','almuerzo',null),
('Bowl de calamar salteado con pasta de maíz','almuerzo',null),
('Ensalada griega de alcachofa y aceitunas kalamata','almuerzo',null),
('Falafel de garbanzo con hongos portobello y hummus','almuerzo',null),
('Enchiladas verdes de pollo con tomatillo y crema agria','almuerzo',null),
('Cena mediterránea de anchoas con pan sin gluten y aceitunas','cena',null),
('Calamar a la plancha con espárragos','cena',null),
('Costilla de res con puré de coliflor','cena',null),
('Cena criolla de chuleta de cerdo con rocoto y huacatay','cena',null),
('Ensalada tibia de pollo molido y trigo sarraceno','cena',null),
('Tofu con hongos portobello y salsa de soya','cena',null),
('Sopa de mejillones y verduras','cena',null),
('Tacos de chorizo con nopal','cena',null),
('Yogur de coco con camu camu','snack',null),
('Yogur de almendra con semillas de cáñamo','snack',null),
('Papaya con lúcuma','snack',null),
('Aceitunas kalamata y queso feta a la griega','snack',null),
('Maracuyá con granola y yogur griego','snack',null),
('Hongos portobello rellenos de queso vegano','snack',null),
('Snack sin gluten de pan multigrano con jamón serrano','snack',null),
('Cancha criolla con levadura nutricional','snack',null),
('Batido de leche de almendra y maracuyá','batido',null),
('Batido de bebida de coco y papaya','batido',null);

-- ---------- RECETAS (dish_ingredients) ----------
insert into dish_ingredients (dish_id, ingredient_id, grams)
select d.id, i.id, v.grams
from (values
  -- Desayunos
  ('Avena proteica','Avena',50),('Avena proteica','Proteína en polvo',45),('Avena proteica','Chía',10),
  ('Bowl griego','Yogur griego natural 0%',250),('Bowl griego','Proteína en polvo',25),('Bowl griego','Granola sin azúcar',25),('Bowl griego','Frutos rojos',50),
  ('Panqueques sin huevo','Avena',50),('Panqueques sin huevo','Proteína en polvo',45),('Panqueques sin huevo','Plátano',60),
  ('Smoothie bowl','Proteína en polvo',45),('Smoothie bowl','Frutos congelados',150),('Smoothie bowl','Avena',30),('Smoothie bowl','Leche vegetal',200),
  ('Desayuno refeed (avena + plátano + miel)','Avena',80),('Desayuno refeed (avena + plátano + miel)','Proteína en polvo',45),('Desayuno refeed (avena + plátano + miel)','Plátano',120),('Desayuno refeed (avena + plátano + miel)','Miel',20),
  -- Batidos
  ('Batido peri-entreno (día pesas)','Proteína en polvo',70),('Batido peri-entreno (día pesas)','Plátano',120),
  ('Batido peri-entreno (día bajo)','Proteína en polvo',60),('Batido peri-entreno (día bajo)','Leche vegetal',150),('Batido peri-entreno (día bajo)','Plátano',60),
  -- Cenas
  ('Cena: yogur griego + cottage + fruta','Yogur griego natural 0%',300),('Cena: yogur griego + cottage + fruta','Queso cottage',100),('Cena: yogur griego + cottage + fruta','Fruta pequeña (manzana)',100),('Cena: yogur griego + cottage + fruta','Chía',15),
  ('Cena: queso fresco a la plancha + palta','Queso fresco',200),('Cena: queso fresco a la plancha + palta','Palta',30),('Cena: queso fresco a la plancha + palta','Verduras mixtas',200),
  ('Cena: crema de verduras + tofu sellado','Tofu firme',200),('Cena: crema de verduras + tofu sellado','Verduras mixtas',250),('Cena: crema de verduras + tofu sellado','Aceite de oliva',5),
  ('Cena exprés: caseína + mantequilla de maní','Caseína en polvo',40),('Cena exprés: caseína + mantequilla de maní','Mantequilla de maní',15),('Cena exprés: caseína + mantequilla de maní','Leche vegetal',200),
  ('Cena refeed: arroz + tofu + verduras','Arroz cocido',100),('Cena refeed: arroz + tofu + verduras','Tofu firme',250),('Cena refeed: arroz + tofu + verduras','Verduras mixtas',100),
  -- Snacks
  ('Snack refeed: pan + mermelada + proteína','Pan de molde',80),('Snack refeed: pan + mermelada + proteína','Mermelada',30),('Snack refeed: pan + mermelada + proteína','Proteína en polvo',30),
  ('Snack diet break: pan con palta','Pan de molde',100),('Snack diet break: pan con palta','Palta',40),('Snack diet break: pan con palta','Proteína en polvo',25),
  ('Snack extra: fruta + yogur','Yogur griego natural 0%',100),('Snack extra: fruta + yogur','Fruta pequeña (manzana)',120),('Snack extra: fruta + yogur','Granola sin azúcar',20),
  -- Shakes de proteína (REQ-76)
  ('Shake de proteína con agua','Proteína en polvo',35),
  ('Shake de proteína con yogur griego','Proteína en polvo',30),('Shake de proteína con yogur griego','Yogur griego natural 0%',200),
  -- Menú A
  ('Saltado de tofu firme + arroz','Tofu firme',250),('Saltado de tofu firme + arroz','Arroz cocido',200),('Saltado de tofu firme + arroz','Cebolla',50),('Saltado de tofu firme + arroz','Tomate',50),('Saltado de tofu firme + arroz','Aceite de oliva',8),
  ('Lentejas guisadas + quinua + ensalada','Lentejas cocidas',350),('Lentejas guisadas + quinua + ensalada','Quinua cocida',120),('Lentejas guisadas + quinua + ensalada','Verduras mixtas',100),('Lentejas guisadas + quinua + ensalada','Aceite de oliva',5),
  ('Tacu tacu de pallares + seitán','Pallares cocidos',250),('Tacu tacu de pallares + seitán','Seitán',120),('Tacu tacu de pallares + seitán','Aceite de oliva',8),
  ('Ají de garbanzos + arroz','Garbanzos cocidos',250),('Ají de garbanzos + arroz','Leche evaporada light',50),('Ají de garbanzos + arroz','Arroz cocido',80),('Ají de garbanzos + arroz','Queso fresco',60),
  ('Quinua atamalada + queso fresco + tofu','Quinua cocida',200),('Quinua atamalada + queso fresco + tofu','Queso fresco',100),('Quinua atamalada + queso fresco + tofu','Tofu firme',150),
  ('Frijoles canarios + arroz + queso fresco','Frijoles canarios cocidos',250),('Frijoles canarios + arroz + queso fresco','Arroz cocido',80),('Frijoles canarios + arroz + queso fresco','Queso fresco',120),
  ('Locro de zapallo con quinua + tofu','Zapallo',200),('Locro de zapallo con quinua + tofu','Quinua cocida',120),('Locro de zapallo con quinua + tofu','Tofu firme',200),
  -- Menú B
  ('Pasta integral + boloñesa de lentejas + parmesano','Pasta integral seca',60),('Pasta integral + boloñesa de lentejas + parmesano','Lentejas cocidas',250),('Pasta integral + boloñesa de lentejas + parmesano','Parmesano',30),('Pasta integral + boloñesa de lentejas + parmesano','Tomate',80),('Pasta integral + boloñesa de lentejas + parmesano','Aceite de oliva',8),
  ('Bowl de hummus + tofu horneado + pita','Hummus',100),('Bowl de hummus + tofu horneado + pita','Tofu firme',150),('Bowl de hummus + tofu horneado + pita','Pan pita integral',50),('Bowl de hummus + tofu horneado + pita','Verduras mixtas',100),
  ('Falafel al horno + tabule de quinua + yogur','Garbanzos cocidos',200),('Falafel al horno + tabule de quinua + yogur','Quinua cocida',120),('Falafel al horno + tabule de quinua + yogur','Yogur griego natural 0%',80),('Falafel al horno + tabule de quinua + yogur','Aceite de oliva',8),
  ('Berenjenas al horno con lentejas + queso fresco','Berenjena',150),('Berenjenas al horno con lentejas + queso fresco','Lentejas cocidas',200),('Berenjenas al horno con lentejas + queso fresco','Queso fresco',120),('Berenjenas al horno con lentejas + queso fresco','Arroz cocido',100),
  ('Risotto de champiñones + tofu','Arroz cocido',200),('Risotto de champiñones + tofu','Champiñones',150),('Risotto de champiñones + tofu','Tofu firme',200),('Risotto de champiñones + tofu','Parmesano',10),
  ('Ensalada griega + garbanzos + queso fresco','Garbanzos cocidos',250),('Ensalada griega + garbanzos + queso fresco','Queso fresco',120),('Ensalada griega + garbanzos + queso fresco','Aceitunas',30),('Ensalada griega + garbanzos + queso fresco','Verduras mixtas',150),
  ('Pisto de verduras + soya texturizada + papa','Soya texturizada (seca)',70),('Pisto de verduras + soya texturizada + papa','Verduras mixtas',200),('Pisto de verduras + soya texturizada + papa','Papa',250),('Pisto de verduras + soya texturizada + papa','Aceite de oliva',10),
  -- Menú C
  ('Tofu teriyaki + arroz + brócoli','Tofu firme',250),('Tofu teriyaki + arroz + brócoli','Arroz cocido',200),('Tofu teriyaki + arroz + brócoli','Brócoli',150),
  ('Curry de garbanzos + arroz','Garbanzos cocidos',250),('Curry de garbanzos + arroz','Leche de coco light',80),('Curry de garbanzos + arroz','Arroz cocido',100),('Curry de garbanzos + arroz','Tofu firme',120),
  ('Salteado de tempeh con pak choi y pimientos','Tempeh',200),('Salteado de tempeh con pak choi y pimientos','Pak choi',150),('Salteado de tempeh con pak choi y pimientos','Pimiento',100),('Salteado de tempeh con pak choi y pimientos','Aceite de oliva',8),('Salteado de tempeh con pak choi y pimientos','Arroz cocido',200),
  ('Pad thai de tofu','Tofu firme',250),('Pad thai de tofu','Fideos de arroz secos',60),('Pad thai de tofu','Maní',15),('Pad thai de tofu','Verduras mixtas',100),
  ('Bowl de edamame + tofu + arroz + palta','Edamame',200),('Bowl de edamame + tofu + arroz + palta','Tofu firme',150),('Bowl de edamame + tofu + arroz + palta','Arroz cocido',120),('Bowl de edamame + tofu + arroz + palta','Palta',30),
  ('Ramen miso con tofu y fideos','Tofu firme',250),('Ramen miso con tofu y fideos','Fideos de trigo secos',60),('Ramen miso con tofu y fideos','Verduras mixtas',100),('Ramen miso con tofu y fideos','Alga nori',5),
  ('Chaufa de quinua con tofu','Quinua cocida',200),('Chaufa de quinua con tofu','Tofu firme',200),('Chaufa de quinua con tofu','Verduras mixtas',100),
  -- Menú D
  ('Burrito bowl de frijol negro','Frijoles negros cocidos',250),('Burrito bowl de frijol negro','Arroz cocido',100),('Burrito bowl de frijol negro','Queso cottage',100),('Burrito bowl de frijol negro','Palta',40),
  ('Chili vegetariano + arroz','Soya texturizada (seca)',60),('Chili vegetariano + arroz','Frijoles negros cocidos',200),('Chili vegetariano + arroz','Tomate',100),('Chili vegetariano + arroz','Arroz cocido',80),('Chili vegetariano + arroz','Aceite de oliva',12),
  ('Tacos de frijol negro y queso fresco','Frijoles negros cocidos',200),('Tacos de frijol negro y queso fresco','Queso fresco',100),('Tacos de frijol negro y queso fresco','Tortilla de maíz',75),('Tacos de frijol negro y queso fresco','Repollo',100),
  ('Fajitas de tofu + tortillas','Tofu firme',250),('Fajitas de tofu + tortillas','Pimiento',100),('Fajitas de tofu + tortillas','Cebolla',50),('Fajitas de tofu + tortillas','Tortilla integral de trigo',75),
  ('Quesadillas de frijol, queso y champiñones','Tortilla integral de trigo',80),('Quesadillas de frijol, queso y champiñones','Frijoles negros cocidos',150),('Quesadillas de frijol, queso y champiñones','Queso fresco',80),('Quesadillas de frijol, queso y champiñones','Champiñones',80),
  ('Enchiladas de frijol + cottage','Frijoles negros cocidos',200),('Enchiladas de frijol + cottage','Tortilla de maíz',75),('Enchiladas de frijol + cottage','Queso cottage',100),('Enchiladas de frijol + cottage','Tomate',50),('Enchiladas de frijol + cottage','Aceite de oliva',10),
  ('Sopa azteca + tofu + palta','Tofu firme',200),('Sopa azteca + tofu + palta','Tortilla de maíz',90),('Sopa azteca + tofu + palta','Palta',40),('Sopa azteca + tofu + palta','Verduras mixtas',150),
  -- Omnívoros
  ('Huevos revueltos + avena','Huevo entero',150),('Huevos revueltos + avena','Avena',60),('Huevos revueltos + avena','Leche vegetal',150),
  ('Pollo a la plancha + arroz + brócoli','Pechuga de pollo',180),('Pollo a la plancha + arroz + brócoli','Arroz cocido',200),('Pollo a la plancha + arroz + brócoli','Brócoli',150),('Pollo a la plancha + arroz + brócoli','Aceite de oliva',8),
  ('Bowl de atún + arroz + palta','Atún en agua',150),('Bowl de atún + arroz + palta','Arroz cocido',200),('Bowl de atún + arroz + palta','Palta',60),
  ('Carne de res salteada + papa + verduras','Carne de res magra',160),('Carne de res salteada + papa + verduras','Papa',220),('Carne de res salteada + papa + verduras','Verduras mixtas',150),('Carne de res salteada + papa + verduras','Aceite de oliva',8),
  ('Salmón al horno + quinua + verduras','Salmón',160),('Salmón al horno + quinua + verduras','Quinua cocida',180),('Salmón al horno + quinua + verduras','Verduras mixtas',150),('Salmón al horno + quinua + verduras','Aceite de oliva',5),
  -- Lote 1 REQ-135
  ('Overnight de avena y skyr','Avena',45),('Overnight de avena y skyr','Skyr natural 0%',200),('Overnight de avena y skyr','Fresa',80),('Overnight de avena y skyr','Chía',10),
  ('Tostadas de palta y huevo','Pan integral',70),('Tostadas de palta y huevo','Palta',50),('Tostadas de palta y huevo','Huevo entero',100),('Tostadas de palta y huevo','Tomate',50),
  ('Wrap de claras y pavo','Wrap integral',65),('Wrap de claras y pavo','Claras pasteurizadas',160),('Wrap de claras y pavo','Pechuga de pavo',60),('Wrap de claras y pavo','Espinaca',40),
  ('Bowl tropical de yogur','Yogur griego natural 0%',200),('Bowl tropical de yogur','Mango',100),('Bowl tropical de yogur','Granola sin azúcar',25),('Bowl tropical de yogur','Proteína en polvo',20),
  ('Avena mani y coco','Avena',55),('Avena mani y coco','Proteína en polvo',30),('Avena mani y coco','Mantequilla de maní',15),('Avena mani y coco','Coco rallado',8),
  ('Arepa con queso fresco','Arepa de maiz',80),('Arepa con queso fresco','Queso fresco',80),('Arepa con queso fresco','Claras pasteurizadas',100),('Arepa con queso fresco','Tomate',60),
  ('Smoothie verde proteico','Proteina vegetal en polvo',35),('Smoothie verde proteico','Leche de soya sin azucar',250),('Smoothie verde proteico','Plátano',80),('Smoothie verde proteico','Espinaca',40),
  ('Pita de pollo y tomate','Pan pita integral',70),('Pita de pollo y tomate','Pollo deshilachado',90),('Pita de pollo y tomate','Tomate',80),('Pita de pollo y tomate','Palta',30),
  ('Panqueques de avena con fresa','Avena',50),('Panqueques de avena con fresa','Claras pasteurizadas',180),('Panqueques de avena con fresa','Fresa',100),('Panqueques de avena con fresa','Miel',10),
  ('Tostadas de ricotta y arandanos','Pan integral',70),('Tostadas de ricotta y arandanos','Ricotta light',90),('Tostadas de ricotta y arandanos','Arandanos',80),('Tostadas de ricotta y arandanos','Chía',10),
  ('Bowl vegano de soya y granola','Yogur de soya natural',220),('Bowl vegano de soya y granola','Proteina vegetal en polvo',25),('Bowl vegano de soya y granola','Granola sin azúcar',30),('Bowl vegano de soya y granola','Frutos rojos',70),
  ('Porridge de quinua y platano','Quinua cocida',180),('Porridge de quinua y platano','Proteína en polvo',30),('Porridge de quinua y platano','Plátano',100),('Porridge de quinua y platano','Leche descremada',150),
  ('Huevos con camote','Huevo entero',140),('Huevos con camote','Camote cocido',200),('Huevos con camote','Espinaca',60),
  ('Cereal integral con leche y fruta','Cereal integral sin azucar',55),('Cereal integral con leche y fruta','Leche descremada',250),('Cereal integral con leche y fruta','Proteína en polvo',20),('Cereal integral con leche y fruta','Fresa',80),
  ('Yogur de soya con frutos rojos','Yogur de soya natural',180),('Yogur de soya con frutos rojos','Proteina vegetal en polvo',20),('Yogur de soya con frutos rojos','Frutos rojos',80),('Yogur de soya con frutos rojos','Linaza molida',10),
  ('Garbanzos tostados con naranja','Garbanzos tostados',45),('Garbanzos tostados con naranja','Naranja',150),
  ('Manzana con mantequilla de almendra','Fruta pequeña (manzana)',140),('Manzana con mantequilla de almendra','Almendras',20),('Manzana con mantequilla de almendra','Proteina vegetal en polvo',15),
  ('Hummus con galletas de arroz','Hummus',80),('Hummus con galletas de arroz','Galletas de arroz',25),('Hummus con galletas de arroz','Pepino',100),
  ('Batido vegetal de platano','Proteina vegetal en polvo',35),('Batido vegetal de platano','Leche de soya sin azucar',250),('Batido vegetal de platano','Plátano',80),
  ('Batido de skyr y mango','Skyr natural 0%',220),('Batido de skyr y mango','Mango',120),('Batido de skyr y mango','Proteína en polvo',20),
  ('Rollitos de pavo y pepino','Jamon de pavo',90),('Rollitos de pavo y pepino','Pepino',120),('Rollitos de pavo y pepino','Galletas de arroz',20),
  ('Cottage con pina','Queso cottage',180),('Cottage con pina','Pina',120),('Cottage con pina','Chía',8),
  ('Almendras y naranja','Almendras',25),('Almendras y naranja','Naranja',160),('Almendras y naranja','Proteina vegetal en polvo',15),
  ('Pita mini de hummus','Pan pita integral',45),('Pita mini de hummus','Hummus',70),('Pita mini de hummus','Zanahoria',80),
  ('Smoothie de soya y fresa','Proteina vegetal en polvo',30),('Smoothie de soya y fresa','Leche de soya sin azucar',250),('Smoothie de soya y fresa','Fresa',120),
  ('Caseina con arandanos','Caseína en polvo',35),('Caseina con arandanos','Arandanos',100),('Caseina con arandanos','Leche descremada',150),
  ('Arepa mini con queso','Arepa de maiz',50),('Arepa mini con queso','Queso fresco',60),('Arepa mini con queso','Tomate',50),
  ('Sardinas con galletas de arroz','Sardinas en agua',80),('Sardinas con galletas de arroz','Galletas de arroz',25),('Sardinas con galletas de arroz','Pepino',100),
  ('Tofu sedoso con mango','Tofu sedoso',180),('Tofu sedoso con mango','Mango',120),('Tofu sedoso con mango','Proteina vegetal en polvo',20),
  ('Edamame con choclo','Edamame',120),('Edamame con choclo','Maiz choclo',80),
  ('Wrap pequeno de pollo','Wrap integral',45),('Wrap pequeno de pollo','Pollo deshilachado',60),('Wrap pequeno de pollo','Lechuga',40),
  ('Datiles con mani','Datiles',30),('Datiles con mani','Maní',25),('Datiles con mani','Proteina vegetal en polvo',20),
  ('Batido tropical vegetal','Proteina vegetal en polvo',30),('Batido tropical vegetal','Leche de soya sin azucar',250),('Batido tropical vegetal','Pina',140),
  ('Pera con nueces y skyr','Pera',150),('Pera con nueces y skyr','Nueces',15),('Pera con nueces y skyr','Skyr natural 0%',150),
  ('Bowl de pollo y camote','Pollo deshilachado',150),('Bowl de pollo y camote','Camote cocido',250),('Bowl de pollo y camote','Brócoli',150),('Bowl de pollo y camote','Aceite de oliva',8),
  ('Ensalada de camarones y quinua','Camarones',180),('Ensalada de camarones y quinua','Quinua cocida',180),('Ensalada de camarones y quinua','Pepino',100),('Ensalada de camarones y quinua','Palta',50),('Ensalada de camarones y quinua','Aceite de oliva',6),
  ('Merluza con arroz integral','Merluza',200),('Merluza con arroz integral','Arroz integral cocido',220),('Merluza con arroz integral','Espinaca',80),('Merluza con arroz integral','Aceite de oliva',8),
  ('Bowl vegano de lenteja roja y bulgur','Lentejas rojas cocidas',260),('Bowl vegano de lenteja roja y bulgur','Bulgur cocido',180),('Bowl vegano de lenteja roja y bulgur','Zanahoria',80),('Bowl vegano de lenteja roja y bulgur','Tahini',15),
  ('Chili de frijol blanco y choclo','Frijoles blancos cocidos',260),('Chili de frijol blanco y choclo','Maiz choclo',120),('Chili de frijol blanco y choclo','Tomate',120),('Chili de frijol blanco y choclo','Arroz integral cocido',120),
  ('Wrap de tempeh y hummus','Wrap integral',80),('Wrap de tempeh y hummus','Tempeh',150),('Wrap de tempeh y hummus','Hummus',80),('Wrap de tempeh y hummus','Espinaca',60),
  ('Pasta de legumbres con tomate y espinaca','Pasta de legumbres seca',80),('Pasta de legumbres con tomate y espinaca','Tomate',150),('Pasta de legumbres con tomate y espinaca','Espinaca',80),('Pasta de legumbres con tomate y espinaca','Aceite de oliva',8),
  ('Arepa de pavo y palta','Arepa de maiz',100),('Arepa de pavo y palta','Pechuga de pavo',130),('Arepa de pavo y palta','Palta',50),('Arepa de pavo y palta','Lechuga',60),
  ('Tilapia con zucchini y cuscus','Tilapia',170),('Tilapia con zucchini y cuscus','Zucchini',200),('Tilapia con zucchini y cuscus','Cuscus cocido',160),('Tilapia con zucchini y cuscus','Aceite de oliva',8),
  ('Trucha con camote y esparragos','Trucha',160),('Trucha con camote y esparragos','Camote cocido',220),('Trucha con camote y esparragos','Esparragos',150),('Trucha con camote y esparragos','Aceite de oliva',5),
  ('Ensalada de tofu sedoso y edamame','Tofu sedoso',250),('Ensalada de tofu sedoso y edamame','Edamame',150),('Ensalada de tofu sedoso y edamame','Arroz integral cocido',100),('Ensalada de tofu sedoso y edamame','Pepino',100),
  ('Sopa de lenteja roja y verduras','Lentejas rojas cocidas',250),('Sopa de lenteja roja y verduras','Verduras mixtas',200),('Sopa de lenteja roja y verduras','Zanahoria',100),('Sopa de lenteja roja y verduras','Aceite de canola',5),
  ('Pollo deshilachado con verduras','Pollo deshilachado',150),('Pollo deshilachado con verduras','Verduras mixtas',250),('Pollo deshilachado con verduras','Papa',180),('Pollo deshilachado con verduras','Aceite de oliva',6),
  ('Sardinas con ensalada y papa','Sardinas en agua',120),('Sardinas con ensalada y papa','Papa',220),('Sardinas con ensalada y papa','Lechuga',100),('Sardinas con ensalada y papa','Tomate',80),
  ('Cuscus con garbanzos y tahini','Cuscus cocido',200),('Cuscus con garbanzos y tahini','Garbanzos cocidos',180),('Cuscus con garbanzos y tahini','Tahini',18),('Cuscus con garbanzos y tahini','Pepino',100),
  ('Cerdo magro con yuca y repollo','Lomo de cerdo magro',160),('Cerdo magro con yuca y repollo','Yuca cocida',180),('Cerdo magro con yuca y repollo','Repollo',150),('Cerdo magro con yuca y repollo','Aceite de canola',6),
  -- Lote 2B REQ-140
  ('Tamal criollo de choclo y queso panela','Maiz choclo',200),('Tamal criollo de choclo y queso panela','Queso panela',60),('Tamal criollo de choclo y queso panela','Aceite de oliva',5),
  ('Sanguche criollo de pollo deshilachado','Pan de molde',90),('Sanguche criollo de pollo deshilachado','Pollo deshilachado',120),('Sanguche criollo de pollo deshilachado','Cebolla',30),('Sanguche criollo de pollo deshilachado','Limón',10),
  ('Cancha criolla con queso fresco','Cancha serrana',40),('Cancha criolla con queso fresco','Queso fresco',60),
  ('Camote criollo con queso panela','Camote cocido',200),('Camote criollo con queso panela','Queso panela',50),
  ('Seco criollo de pollo con frijoles canarios','Pechuga de pollo',160),('Seco criollo de pollo con frijoles canarios','Ají amarillo',20),('Seco criollo de pollo con frijoles canarios','Frijoles canarios cocidos',200),('Seco criollo de pollo con frijoles canarios','Cilantro',5),('Seco criollo de pollo con frijoles canarios','Arroz cocido',150),
  ('Cau cau criollo de pollo y papas','Pollo deshilachado',150),('Cau cau criollo de pollo y papas','Papa',200),('Cau cau criollo de pollo y papas','Ají amarillo',15),('Cau cau criollo de pollo y papas','Cebolla',40),
  ('Tostada mediterranea con hummus y tomate','Pan integral de centeno',70),('Tostada mediterranea con hummus y tomate','Hummus',80),('Tostada mediterranea con hummus y tomate','Tomate',60),('Tostada mediterranea con hummus y tomate','Aceitunas',20),
  ('Pan pita con queso feta y aceitunas','Pan pita integral',60),('Pan pita con queso feta y aceitunas','Queso feta',60),('Pan pita con queso feta y aceitunas','Aceitunas',25),('Pan pita con queso feta y aceitunas','Pepino',60),
  ('Hummus con bastones de pepino y zanahoria','Hummus',100),('Hummus con bastones de pepino y zanahoria','Pepino',100),('Hummus con bastones de pepino y zanahoria','Zanahoria',80),
  ('Mini pita con falafel','Pan pita integral',45),('Mini pita con falafel','Garbanzos cocidos',150),('Mini pita con falafel','Aceite de oliva',8),
  ('Cuscus mediterraneo con garbanzos y aceitunas','Cuscus cocido',200),('Cuscus mediterraneo con garbanzos y aceitunas','Garbanzos cocidos',150),('Cuscus mediterraneo con garbanzos y aceitunas','Aceitunas',25),('Cuscus mediterraneo con garbanzos y aceitunas','Rúcula',40),
  ('Ensalada griega con pollo a la plancha','Pechuga de pollo',150),('Ensalada griega con pollo a la plancha','Queso feta',60),('Ensalada griega con pollo a la plancha','Aceitunas',25),('Ensalada griega con pollo a la plancha','Tomate',80),('Ensalada griega con pollo a la plancha','Pepino',80),
  ('Huevos rancheros estilo azteca','Huevo entero',150),('Huevos rancheros estilo azteca','Salsa de tomate natural',100),('Huevos rancheros estilo azteca','Tortilla de maíz',60),('Huevos rancheros estilo azteca','Frijoles negros cocidos',150),
  ('Tacos de huevo y frijol','Tortilla de maíz',75),('Tacos de huevo y frijol','Huevo entero',120),('Tacos de huevo y frijol','Frijoles negros cocidos',150),('Tacos de huevo y frijol','Chile jalapeño',15),
  ('Mini quesadilla de frijol y queso panela','Tortilla integral de trigo',70),('Mini quesadilla de frijol y queso panela','Frijoles negros cocidos',120),('Mini quesadilla de frijol y queso panela','Queso panela',60),
  ('Nachos ligeros estilo azteca','Tortilla de maíz',60),('Nachos ligeros estilo azteca','Frijoles pintos cocidos',150),('Nachos ligeros estilo azteca','Queso fresco',60),('Nachos ligeros estilo azteca','Chile jalapeño',15),
  ('Fajitas de pollo con pimientos','Pechuga de pollo',170),('Fajitas de pollo con pimientos','Pimiento',120),('Fajitas de pollo con pimientos','Cebolla',60),('Fajitas de pollo con pimientos','Tortilla integral de trigo',75),
  ('Enchiladas de pollo con frijoles rojos','Pollo deshilachado',150),('Enchiladas de pollo con frijoles rojos','Tortilla de maíz',75),('Enchiladas de pollo con frijoles rojos','Frijoles rojos cocidos',150),('Enchiladas de pollo con frijoles rojos','Salsa de tomate natural',80),
  ('Onigiri de edamame y atún','Arroz cocido',180),('Onigiri de edamame y atún','Edamame',100),('Onigiri de edamame y atún','Atún en agua',100),('Onigiri de edamame y atún','Alga nori',5),
  ('Bowl de arroz y pak choi al vapor','Arroz cocido',180),('Bowl de arroz y pak choi al vapor','Pak choi',150),('Bowl de arroz y pak choi al vapor','Huevo entero',100),('Bowl de arroz y pak choi al vapor','Salsa de soya',10),
  ('Edamame con sal marina','Edamame',200),
  ('Pepino con salsa teriyaki y ajonjolí','Pepino',200),('Pepino con salsa teriyaki y ajonjolí','Salsa teriyaki',20),('Pepino con salsa teriyaki y ajonjolí','Ajonjolí',8),
  ('Pad thai de camarones','Camarones',180),('Pad thai de camarones','Fideos de arroz secos',60),('Pad thai de camarones','Maní',20),('Pad thai de camarones','Brotes de soya',100),
  ('Ramen de pollo, pak choi y miso','Pechuga de pollo',150),('Ramen de pollo, pak choi y miso','Fideos de trigo secos',60),('Ramen de pollo, pak choi y miso','Pak choi',120),('Ramen de pollo, pak choi y miso','Pasta de miso',20),('Ramen de pollo, pak choi y miso','Jengibre',8),
  ('Bowl de pollo, arroz y frijoles negros','Pechuga de pollo',160),('Bowl de pollo, arroz y frijoles negros','Arroz cocido',180),('Bowl de pollo, arroz y frijoles negros','Frijoles negros cocidos',150),('Bowl de pollo, arroz y frijoles negros','Pimiento',60),
  ('Ensalada de atún con garbanzos y limón','Atún en agua',150),('Ensalada de atún con garbanzos y limón','Garbanzos cocidos',200),('Ensalada de atún con garbanzos y limón','Limón',15),('Ensalada de atún con garbanzos y limón','Cebolla',30),
  ('Tacos de pollo con frijoles pintos','Pollo deshilachado',150),('Tacos de pollo con frijoles pintos','Tortilla de maíz',75),('Tacos de pollo con frijoles pintos','Frijoles pintos cocidos',150),('Tacos de pollo con frijoles pintos','Repollo',80),
  ('Pasta integral con atún y tomate','Pasta integral seca',70),('Pasta integral con atún y tomate','Atún en agua',150),('Pasta integral con atún y tomate','Salsa de tomate natural',100),('Pasta integral con atún y tomate','Aceitunas',20),
  ('Bowl de huevo, camote y espinaca','Huevo entero',150),('Bowl de huevo, camote y espinaca','Camote cocido',220),('Bowl de huevo, camote y espinaca','Espinaca',60),('Bowl de huevo, camote y espinaca','Aceite de oliva',8),
  ('Yogur griego con nueces y miel','Yogur griego natural 0%',220),('Yogur griego con nueces y miel','Nueces',20),('Yogur griego con nueces y miel','Miel',15),
  ('Requesón con higos y avellanas','Requesón',180),('Requesón con higos y avellanas','Higos secos',40),('Requesón con higos y avellanas','Avellanas',15),
  ('Bacalao al horno con papas y coliflor','Bacalao desalado',180),('Bacalao al horno con papas y coliflor','Papa',200),('Bacalao al horno con papas y coliflor','Coliflor',150),('Bacalao al horno con papas y coliflor','Aceite de oliva',8),
  ('Pulpo a la parrilla con papas doradas','Pulpo cocido',180),('Pulpo a la parrilla con papas doradas','Papa',200),('Pulpo a la parrilla con papas doradas','Pimiento',60),('Pulpo a la parrilla con papas doradas','Aceite de oliva',8),
  ('Ensalada de lomo fino con rúcula y granada','Lomo fino de res',160),('Ensalada de lomo fino con rúcula y granada','Rúcula',60),('Ensalada de lomo fino con rúcula y granada','Granada',60),('Ensalada de lomo fino con rúcula y granada','Aceite de oliva',6),
  ('Huevos de codorniz con palta y tostada','Huevo de codorniz',120),('Huevos de codorniz con palta y tostada','Palta',60),('Huevos de codorniz con palta y tostada','Pan integral de centeno',60),
  ('Bowl de betarraga, garbanzos y queso feta','Betarraga',120),('Bowl de betarraga, garbanzos y queso feta','Garbanzos cocidos',180),('Bowl de betarraga, garbanzos y queso feta','Queso feta',60),('Bowl de betarraga, garbanzos y queso feta','Rúcula',40),
  ('Salteado de setas shiitake y tofu','Setas shiitake',150),('Salteado de setas shiitake y tofu','Tofu firme',200),('Salteado de setas shiitake y tofu','Salsa de soya',12),('Salteado de setas shiitake y tofu','Jengibre',8),
  ('Ensalada de col morada, rábano y pepinillos','Col morada',120),('Ensalada de col morada, rábano y pepinillos','Rábano',80),('Ensalada de col morada, rábano y pepinillos','Pepinillos encurtidos',60),('Ensalada de col morada, rábano y pepinillos','Aceite de oliva',6),
  ('Batido de leche entera, plátano y avena','Leche entera',250),('Batido de leche entera, plátano y avena','Plátano',100),('Batido de leche entera, plátano y avena','Avena',40),('Batido de leche entera, plátano y avena','Miel',10),
  ('Batido de sandía y limón','Sandía',300),('Batido de sandía y limón','Limón',15),('Batido de sandía y limón','Miel',10),
  ('Ensalada de melón y jamón de pavo','Melón',200),('Ensalada de melón y jamón de pavo','Jamon de pavo',80),
  ('Bowl de kiwi, yogur griego y semillas de girasol','Kiwi',120),('Bowl de kiwi, yogur griego y semillas de girasol','Yogur griego natural 0%',200),('Bowl de kiwi, yogur griego y semillas de girasol','Semillas de girasol',15),('Bowl de kiwi, yogur griego y semillas de girasol','Granola sin azúcar',20),
  ('Sopa de puerro y papa','Puerro',150),('Sopa de puerro y papa','Papa',200),('Sopa de puerro y papa','Leche entera',150),('Sopa de puerro y papa','Aceite de oliva',6),
  ('Ensalada de nabo, zanahoria y pollo','Nabo',100),('Ensalada de nabo, zanahoria y pollo','Zanahoria',80),('Ensalada de nabo, zanahoria y pollo','Pechuga de pollo',150),('Ensalada de nabo, zanahoria y pollo','Aceite de sésamo',6),
  ('Snack de ciruelas pasas y almendras','Ciruelas pasas',40),('Snack de ciruelas pasas y almendras','Almendras',20),
  -- Lote 2C REQ-141
  ('Bowl de papaya y maracuyá con yogur de coco','Papaya',150),('Bowl de papaya y maracuyá con yogur de coco','Maracuyá',80),('Bowl de papaya y maracuyá con yogur de coco','Yogur de coco natural',200),('Bowl de papaya y maracuyá con yogur de coco','Granola sin azúcar',25),
  ('Panqueques de harina de almendra y arroz','Harina de almendra',40),('Panqueques de harina de almendra y arroz','Harina de arroz',20),('Panqueques de harina de almendra y arroz','Huevo entero',100),('Panqueques de harina de almendra y arroz','Leche de almendra sin azúcar',100),('Panqueques de harina de almendra y arroz','Miel',15),
  ('Porridge de trigo sarraceno y amaranto con frutos rojos','Trigo sarraceno cocido',100),('Porridge de trigo sarraceno y amaranto con frutos rojos','Amaranto cocido',100),('Porridge de trigo sarraceno y amaranto con frutos rojos','Leche de almendra sin azúcar',150),('Porridge de trigo sarraceno y amaranto con frutos rojos','Frutos rojos',60),('Porridge de trigo sarraceno y amaranto con frutos rojos','Chía',10),
  ('Tostadas sin gluten con palta y huevo','Pan sin gluten multigrano',70),('Tostadas sin gluten con palta y huevo','Palta',60),('Tostadas sin gluten con palta y huevo','Huevo entero',100),
  ('Bowl criollo de camote, huevo y ají amarillo','Camote cocido',200),('Bowl criollo de camote, huevo y ají amarillo','Huevo entero',120),('Bowl criollo de camote, huevo y ají amarillo','Ají amarillo',15),('Bowl criollo de camote, huevo y ají amarillo','Cebolla',20),
  ('Yogur de almendra con lúcuma y granola','Yogur de almendra natural',220),('Yogur de almendra con lúcuma y granola','Lúcuma',40),('Yogur de almendra con lúcuma y granola','Granola sin azúcar',25),
  ('Pita con jamón serrano y tomate','Pan pita integral',60),('Pita con jamón serrano y tomate','Jamón serrano',60),('Pita con jamón serrano y tomate','Tomate',60),('Pita con jamón serrano y tomate','Aceite de oliva',6),
  ('Tostadas mexicanas de tomatillo y huevo','Tortilla de maíz',80),('Tostadas mexicanas de tomatillo y huevo','Tomatillo',120),('Tostadas mexicanas de tomatillo y huevo','Huevo entero',100),('Tostadas mexicanas de tomatillo y huevo','Queso panela',40),
  ('Bowl asiático de pollo molido, arroz y pak choi','Pollo molido',180),('Bowl asiático de pollo molido, arroz y pak choi','Arroz cocido',180),('Bowl asiático de pollo molido, arroz y pak choi','Pak choi',120),('Bowl asiático de pollo molido, arroz y pak choi','Salsa de soya',10),
  ('Ensalada de mejillones con quinua y limón','Mejillones cocidos',180),('Ensalada de mejillones con quinua y limón','Quinua cocida',150),('Ensalada de mejillones con quinua y limón','Limón',15),('Ensalada de mejillones con quinua y limón','Aceite de oliva',8),('Ensalada de mejillones con quinua y limón','Rúcula',40),
  ('Tacos de nopal y frijol negro','Nopal',150),('Tacos de nopal y frijol negro','Frijoles negros cocidos',150),('Tacos de nopal y frijol negro','Tortilla de maíz',80),('Tacos de nopal y frijol negro','Chipotle en adobo',15),
  ('Chuleta de cerdo con puré de camote y coles de Bruselas','Chuleta de cerdo',170),('Chuleta de cerdo con puré de camote y coles de Bruselas','Camote cocido',200),('Chuleta de cerdo con puré de camote y coles de Bruselas','Coles de Bruselas',120),('Chuleta de cerdo con puré de camote y coles de Bruselas','Aceite de oliva',6),
  ('Seco criollo de costilla con frijoles canarios y ají panca','Costilla de res',150),('Seco criollo de costilla con frijoles canarios y ají panca','Frijoles canarios cocidos',180),('Seco criollo de costilla con frijoles canarios y ají panca','Ají panca',10),('Seco criollo de costilla con frijoles canarios y ají panca','Cilantro',5),
  ('Bowl de calamar salteado con pasta de maíz','Calamar cocido',170),('Bowl de calamar salteado con pasta de maíz','Pasta de maíz cocida',150),('Bowl de calamar salteado con pasta de maíz','Pimiento',80),('Bowl de calamar salteado con pasta de maíz','Jengibre',8),
  ('Ensalada griega de alcachofa y aceitunas kalamata','Alcachofa cocida',150),('Ensalada griega de alcachofa y aceitunas kalamata','Aceitunas kalamata',40),('Ensalada griega de alcachofa y aceitunas kalamata','Queso feta',50),('Ensalada griega de alcachofa y aceitunas kalamata','Tomate',80),('Ensalada griega de alcachofa y aceitunas kalamata','Berros',30),('Ensalada griega de alcachofa y aceitunas kalamata','Aceite de oliva',8),
  ('Falafel de garbanzo con hongos portobello y hummus','Garbanzos cocidos',180),('Falafel de garbanzo con hongos portobello y hummus','Harina de garbanzo',30),('Falafel de garbanzo con hongos portobello y hummus','Hongos portobello',100),('Falafel de garbanzo con hongos portobello y hummus','Hummus',60),('Falafel de garbanzo con hongos portobello y hummus','Aceite de oliva',8),
  ('Enchiladas verdes de pollo con tomatillo y crema agria','Pollo deshilachado',160),('Enchiladas verdes de pollo con tomatillo y crema agria','Tomatillo',150),('Enchiladas verdes de pollo con tomatillo y crema agria','Tortilla de maíz',80),('Enchiladas verdes de pollo con tomatillo y crema agria','Crema agria light',30),
  ('Cena mediterránea de anchoas con pan sin gluten y aceitunas','Anchoas en aceite',60),('Cena mediterránea de anchoas con pan sin gluten y aceitunas','Pan sin gluten multigrano',60),('Cena mediterránea de anchoas con pan sin gluten y aceitunas','Aceitunas kalamata',30),('Cena mediterránea de anchoas con pan sin gluten y aceitunas','Tomate',60),
  ('Calamar a la plancha con espárragos','Calamar cocido',180),('Calamar a la plancha con espárragos','Esparragos',150),('Calamar a la plancha con espárragos','Aceite de oliva',8),('Calamar a la plancha con espárragos','Limón',10),
  ('Costilla de res con puré de coliflor','Costilla de res',160),('Costilla de res con puré de coliflor','Coliflor',200),('Costilla de res con puré de coliflor','Aceite de oliva',6),
  ('Cena criolla de chuleta de cerdo con rocoto y huacatay','Chuleta de cerdo',160),('Cena criolla de chuleta de cerdo con rocoto y huacatay','Rocoto',20),('Cena criolla de chuleta de cerdo con rocoto y huacatay','Camote cocido',180),('Cena criolla de chuleta de cerdo con rocoto y huacatay','Cebolla',30),('Cena criolla de chuleta de cerdo con rocoto y huacatay','Huacatay',5),
  ('Ensalada tibia de pollo molido y trigo sarraceno','Pollo molido',150),('Ensalada tibia de pollo molido y trigo sarraceno','Trigo sarraceno cocido',150),('Ensalada tibia de pollo molido y trigo sarraceno','Espinaca',60),('Ensalada tibia de pollo molido y trigo sarraceno','Aceite de oliva',8),
  ('Tofu con hongos portobello y salsa de soya','Tofu firme',180),('Tofu con hongos portobello y salsa de soya','Hongos portobello',150),('Tofu con hongos portobello y salsa de soya','Salsa de soya',12),('Tofu con hongos portobello y salsa de soya','Jengibre',6),
  ('Sopa de mejillones y verduras','Mejillones cocidos',150),('Sopa de mejillones y verduras','Zanahoria',60),('Sopa de mejillones y verduras','Apio',40),('Sopa de mejillones y verduras','Cebolla',40),
  ('Tacos de chorizo con nopal','Chorizo criollo',100),('Tacos de chorizo con nopal','Nopal',150),('Tacos de chorizo con nopal','Tortilla de maíz',75),('Tacos de chorizo con nopal','Cebolla',30),
  ('Yogur de coco con camu camu','Yogur de coco natural',200),('Yogur de coco con camu camu','Camu camu',30),('Yogur de coco con camu camu','Miel',10),
  ('Yogur de almendra con semillas de cáñamo','Yogur de almendra natural',200),('Yogur de almendra con semillas de cáñamo','Semillas de cáñamo',15),('Yogur de almendra con semillas de cáñamo','Frutos rojos',40),
  ('Papaya con lúcuma','Papaya',200),('Papaya con lúcuma','Lúcuma',30),
  ('Aceitunas kalamata y queso feta a la griega','Aceitunas kalamata',60),('Aceitunas kalamata y queso feta a la griega','Queso feta',50),
  ('Maracuyá con granola y yogur griego','Maracuyá',100),('Maracuyá con granola y yogur griego','Granola sin azúcar',30),('Maracuyá con granola y yogur griego','Yogur griego natural 0%',100),
  ('Hongos portobello rellenos de queso vegano','Hongos portobello',150),('Hongos portobello rellenos de queso vegano','Queso vegano rallado',40),('Hongos portobello rellenos de queso vegano','Aceite de oliva',6),
  ('Snack sin gluten de pan multigrano con jamón serrano','Pan sin gluten multigrano',50),('Snack sin gluten de pan multigrano con jamón serrano','Jamón serrano',50),('Snack sin gluten de pan multigrano con jamón serrano','Tomate',30),
  ('Cancha criolla con levadura nutricional','Cancha serrana',60),('Cancha criolla con levadura nutricional','Levadura nutricional',10),
  ('Batido de leche de almendra y maracuyá','Leche de almendra sin azúcar',250),('Batido de leche de almendra y maracuyá','Maracuyá',60),('Batido de leche de almendra y maracuyá','Miel',10),('Batido de leche de almendra y maracuyá','Proteína en polvo',30),
  ('Batido de bebida de coco y papaya','Bebida de coco sin azúcar',250),('Batido de bebida de coco y papaya','Papaya',150),('Batido de bebida de coco y papaya','Proteína en polvo',30)
) as v(dish_name, ing_name, grams)
join dishes d      on d.name = v.dish_name
join ingredients i on i.name = v.ing_name;

-- ---------- DIETAS ----------
insert into diets (code, name, description) values
('A','Menú A — Criollo','Semanas 1, 5, 10'),
('B','Menú B — Mediterráneo','Semanas 2, 7 (y base del diet break)'),
('C','Menú C — Asiático','Semanas 3, 8'),
('D','Menú D — Mexicano','Semanas 4, 9');

-- ---------- ASIGNACIÓN de almuerzos por día (1=Lun .. 6=Sáb, 0=Dom) ----------
insert into diet_dishes (diet_id, dish_id, weekday, slot)
select dt.id, d.id, v.weekday, 'almuerzo'
from (values
  ('A','Saltado de tofu firme + arroz',1),
  ('A','Lentejas guisadas + quinua + ensalada',2),
  ('A','Tacu tacu de pallares + seitán',3),
  ('A','Ají de garbanzos + arroz',4),
  ('A','Quinua atamalada + queso fresco + tofu',5),
  ('A','Frijoles canarios + arroz + queso fresco',6),
  ('A','Locro de zapallo con quinua + tofu',0),
  ('B','Pasta integral + boloñesa de lentejas + parmesano',1),
  ('B','Bowl de hummus + tofu horneado + pita',2),
  ('B','Falafel al horno + tabule de quinua + yogur',3),
  ('B','Berenjenas al horno con lentejas + queso fresco',4),
  ('B','Risotto de champiñones + tofu',5),
  ('B','Ensalada griega + garbanzos + queso fresco',6),
  ('B','Pisto de verduras + soya texturizada + papa',0),
  ('C','Tofu teriyaki + arroz + brócoli',1),
  ('C','Curry de garbanzos + arroz',2),
  ('C','Salteado de tempeh con pak choi y pimientos',3),
  ('C','Pad thai de tofu',4),
  ('C','Bowl de edamame + tofu + arroz + palta',5),
  ('C','Ramen miso con tofu y fideos',6),
  ('C','Chaufa de quinua con tofu',0),
  ('D','Burrito bowl de frijol negro',1),
  ('D','Chili vegetariano + arroz',2),
  ('D','Tacos de frijol negro y queso fresco',3),
  ('D','Fajitas de tofu + tortillas',4),
  ('D','Quesadillas de frijol, queso y champiñones',5),
  ('D','Enchiladas de frijol + cottage',6),
  ('D','Sopa azteca + tofu + palta',0)
) as v(diet_code, dish_name, weekday)
join diets dt on dt.code = v.diet_code
join dishes d on d.name = v.dish_name;
