(function(root){
  "use strict";

  const OWN_MEDIA={
    media_type:"inline_svg",
    source_name:"Fitbros Studio",
    source_url:"",
    license_name:"Contenido propio Fitbros",
    attribution:"Fitbros Studio",
    active:true,
  };

  const PATTERNS={
    squat:{
      start_position:"Pies firmes, tronco alto y abdomen activo.",
      steps:["Lleva la cadera atrás y flexiona las rodillas con control.","Desciende hasta el rango que puedas mantener sin dolor.","Empuja el suelo y vuelve a la posición inicial sin perder alineación."],
      breathing:"Inhala antes de bajar, mantén el abdomen firme y exhala al subir.",
      common_errors:["Rodillas colapsando hacia dentro","Talones despegados","Perder la postura del tronco"],
      safety_signals:["Dolor agudo de rodilla, cadera o espalda","Mareo o pérdida de equilibrio"],
      contraindications:["dolor agudo de rodilla","lesión reciente de cadera"],
      media_key:"squat",
    },
    hinge:{
      start_position:"Pies al ancho de cadera, rodillas suaves y columna neutra.",
      steps:["Empuja la cadera hacia atrás manteniendo la carga cerca del cuerpo.","Baja solo mientras conserves la espalda estable.","Aprieta glúteos y lleva la cadera hacia delante para volver."],
      breathing:"Inhala y bloquea el tronco antes de bajar; exhala al extender la cadera.",
      common_errors:["Redondear la espalda","Convertir el movimiento en sentadilla","Separar la carga del cuerpo"],
      safety_signals:["Dolor punzante lumbar","Hormigueo o dolor irradiado"],
      contraindications:["dolor lumbar agudo","lesión reciente de isquiotibiales"],
      media_key:"hinge",
    },
    push:{
      start_position:"Manos estables, hombros lejos de las orejas y tronco firme.",
      steps:["Baja la carga o el cuerpo con los codos controlados.","Mantén muñecas, hombros y tronco alineados.","Empuja hasta extender sin bloquear con violencia."],
      breathing:"Inhala al bajar y exhala durante el empuje.",
      common_errors:["Hombros elevados","Codos sin control","Arquear la zona lumbar"],
      safety_signals:["Dolor agudo de hombro, codo o muñeca","Pérdida súbita de fuerza"],
      contraindications:["dolor agudo de hombro","lesión reciente de muñeca"],
      media_key:"push",
    },
    pull:{
      start_position:"Agarre firme, pecho abierto y hombros alejados de las orejas.",
      steps:["Inicia llevando los hombros atrás y abajo.","Acerca la carga o el cuerpo sin balancearte.","Regresa lentamente hasta recuperar el rango completo."],
      breathing:"Exhala al tirar e inhala al volver.",
      common_errors:["Encoger los hombros","Usar impulso","Acortar el regreso"],
      safety_signals:["Dolor agudo de hombro o codo","Hormigueo en brazo o mano"],
      contraindications:["dolor agudo de hombro","lesión reciente de codo"],
      media_key:"pull",
    },
    lunge:{
      start_position:"Tronco alto, pies separados y mirada al frente.",
      steps:["Da un paso estable y reparte el peso entre ambos pies.","Baja la rodilla posterior con control sin golpear el suelo.","Empuja con el pie delantero para volver o avanzar."],
      breathing:"Inhala al bajar y exhala al subir.",
      common_errors:["Paso demasiado corto","Rodilla colapsando hacia dentro","Perder el equilibrio"],
      safety_signals:["Dolor agudo de rodilla o cadera","Inestabilidad que no mejora al reducir rango"],
      contraindications:["dolor agudo de rodilla","problemas de equilibrio no evaluados"],
      media_key:"lunge",
    },
    bridge:{
      start_position:"Apoya la espalda y los pies con la pelvis neutra.",
      steps:["Activa el abdomen antes de mover la cadera.","Eleva la pelvis apretando glúteos sin arquear la espalda.","Pausa arriba y baja de forma controlada."],
      breathing:"Exhala al elevar la cadera e inhala al bajar.",
      common_errors:["Empujar solo con la zona lumbar","Pies demasiado lejos","Rodillas abriéndose o cerrándose"],
      safety_signals:["Dolor lumbar o de cadera","Calambre persistente"],
      contraindications:["dolor lumbar agudo","lesión reciente de cadera"],
      media_key:"bridge",
    },
    core:{
      start_position:"Columna neutra, abdomen activo y respiración continua.",
      steps:["Crea tensión suave antes de mover brazos o piernas.","Mantén pelvis y costillas estables durante el ejercicio.","Detén la serie cuando pierdas la postura."],
      breathing:"Respira corto y continuo; no aguantes el aire por tiempo prolongado.",
      common_errors:["Contener la respiración","Arquear la zona lumbar","Continuar después de perder postura"],
      safety_signals:["Dolor lumbar o cervical","Mareo al sostener la posición"],
      contraindications:["dolor lumbar agudo","cirugía abdominal reciente"],
      media_key:"core",
    },
    calf:{
      start_position:"Pies paralelos, apoyo estable y rodillas suaves.",
      steps:["Eleva los talones manteniendo el peso sobre el primer y segundo dedo.","Pausa arriba sin perder equilibrio.","Baja lentamente hasta apoyar por completo."],
      breathing:"Exhala al subir e inhala al bajar.",
      common_errors:["Rebotar","Girar los tobillos","Acortar el descenso"],
      safety_signals:["Dolor agudo de tobillo o pantorrilla","Pérdida de equilibrio"],
      contraindications:["lesión reciente de Aquiles","dolor agudo de tobillo"],
      media_key:"calf",
    },
    isolation:{
      start_position:"Articulación estable y recorrido cómodo sin impulso.",
      steps:["Ajusta la carga para controlar todo el movimiento.","Mueve solo la articulación objetivo.","Regresa lentamente sin dejar caer la carga."],
      breathing:"Exhala durante el esfuerzo e inhala al volver.",
      common_errors:["Usar impulso","Carga excesiva","Recorrido doloroso"],
      safety_signals:["Dolor agudo articular","Hormigueo o pérdida de control"],
      contraindications:["dolor agudo en la articulación trabajada"],
      media_key:"isolation",
    },
    run:{
      start_position:"Postura alta, mirada al frente y pasos suaves bajo el cuerpo.",
      steps:["Comienza a ritmo fácil para estabilizar respiración y técnica.","Completa el bloque indicado manteniendo una zancada controlada.","Reduce el ritmo durante la recuperación y detente si aparece una señal de alerta."],
      breathing:"Usa una respiración rítmica y recupera el habla durante los tramos suaves.",
      common_errors:["Salir demasiado rápido","Alargar la zancada por delante del cuerpo","Ignorar dolor creciente"],
      safety_signals:["Dolor de pecho, mareo o falta de aire inusual","Dolor articular que cambia la técnica"],
      contraindications:["dolor agudo al correr","señales cardiovasculares no evaluadas"],
      media_key:"run",
    },
    cycle:{
      start_position:"Bicicleta estable, sillín ajustado y manos relajadas.",
      steps:["Pedalea suave hasta encontrar una cadencia estable.","Completa los bloques sin balancear excesivamente el tronco.","Recupera con resistencia baja y termina con pedaleo fácil."],
      breathing:"Mantén respiración rítmica; baja la intensidad si no puedes recuperarla.",
      common_errors:["Resistencia excesiva","Caderas balanceándose","Bloquear hombros y manos"],
      safety_signals:["Dolor de pecho, mareo o adormecimiento persistente","Dolor agudo de rodilla"],
      contraindications:["dolor agudo de rodilla","señales cardiovasculares no evaluadas"],
      media_key:"cycle",
    },
    swim:{
      start_position:"Cuerpo alineado, cuello relajado y respiración preparada.",
      steps:["Nada suave hasta estabilizar la técnica.","Mantén alineación y agarre antes de aumentar el ritmo.","Usa las pausas indicadas y sal del agua ante cualquier señal de alerta."],
      breathing:"Exhala dentro del agua y toma aire sin levantar en exceso la cabeza.",
      common_errors:["Acelerar perdiendo alineación","Contener el aire","Cruzar la mano delante de la cabeza"],
      safety_signals:["Mareo, dificultad respiratoria o desorientación","Dolor agudo de hombro"],
      contraindications:["no saber nadar con seguridad","dolor agudo de hombro"],
      media_key:"swim",
    },
  };

  function exercise(spec){
    const pattern=PATTERNS[spec.pattern];
    return Object.assign({},OWN_MEDIA,{
      slug:spec.slug,
      name:spec.name,
      aliases:spec.aliases||[],
      discipline:spec.discipline,
      level:spec.level||"beginner",
      equipment:spec.equipment||[],
      places:spec.places||[],
      muscles:spec.muscles||[],
      movement_pattern:spec.pattern,
      start_position:spec.start_position||pattern.start_position,
      steps:spec.steps||pattern.steps,
      breathing:spec.breathing||pattern.breathing,
      common_errors:spec.common_errors||pattern.common_errors,
      safety_signals:spec.safety_signals||pattern.safety_signals,
      regression:spec.regression,
      progression:spec.progression,
      substitute_slugs:spec.substitutes||[],
      contraindications:spec.contraindications||pattern.contraindications,
      media_key:spec.media_key||pattern.media_key,
      static_key:spec.media_key||pattern.media_key,
    });
  }

  const strength=[
    ["back-squat","Sentadilla con barra",["sentadilla"],"gym","squat",["barbell","rack"],["gym"],["cuádriceps","glúteos"],"Sentadilla a caja","Sentadilla frontal",["tempo-squat","leg-press"]],
    ["bench-press","Press de banca",["press banca"],"gym","push",["barbell","bench"],["gym"],["pecho","tríceps"],"Press con mancuernas ligeras","Press con pausa",["push-up","incline-dumbbell-press"]],
    ["seated-cable-row","Remo sentado en polea",["remo sentado"],"gym","pull",["cable"],["gym"],["espalda","bíceps"],"Remo con banda","Remo con pausa",["band-row","lat-pulldown"]],
    ["romanian-deadlift","Peso muerto rumano",["RDL"],"gym","hinge",["barbell"],["gym"],["isquiotibiales","glúteos"],"Bisagra con palo","Peso muerto rumano a una pierna",["single-leg-rdl","barbell-hip-thrust"]],
    ["barbell-hip-thrust","Hip thrust",["empuje de cadera"],"gym","bridge",["barbell","bench"],["gym"],["glúteos","isquiotibiales"],"Puente de glúteo","Hip thrust con pausa",["glute-bridge","single-leg-glute-bridge"]],
    ["incline-dumbbell-press","Press inclinado con mancuernas",["press inclinado"],"gym","push",["dumbbells","bench"],["gym"],["pecho","hombros","tríceps"],"Press inclinado ligero","Press alternado",["bench-press","incline-push-up"]],
    ["lat-pulldown","Jalón al pecho",["jalón"],"gym","pull",["cable"],["gym"],["dorsales","bíceps"],"Jalón con banda","Dominada asistida",["assisted-pull-up","band-row"]],
    ["bulgarian-split-squat","Sentadilla búlgara",["búlgara"],"strength","lunge",["bench_or_chair"],["gym","home"],["cuádriceps","glúteos"],"Zancada estática","Búlgara con carga",["walking-lunge","step-up"]],
    ["overhead-press","Press militar",["press sobre cabeza"],"gym","push",["barbell_or_dumbbells"],["gym"],["hombros","tríceps"],"Press sentado ligero","Press de pie con pausa",["pike-push-up","incline-dumbbell-press"]],
    ["walking-lunge","Zancada",["lunges"],"strength","lunge",[],["gym","home","outdoor"],["cuádriceps","glúteos"],"Zancada asistida","Zancada caminando con carga",["bulgarian-split-squat","step-up"]],
    ["standing-calf-raise","Elevación de gemelos",["gemelos"],"strength","calf",[],["gym","home"],["pantorrillas"],"Elevación con apoyo","Elevación a una pierna",[]],
    ["assisted-dip","Fondos asistidos",["fondos"],"strength","push",["bench_or_assistance"],["gym","home"],["pecho","tríceps"],"Flexión inclinada","Fondos con menor asistencia",["incline-push-up","push-up"]],
    ["biceps-curl","Curl de bíceps",["curl"],"gym","isolation",["dumbbells_or_cable"],["gym"],["bíceps"],"Curl con banda ligera","Curl alternado controlado",["band-row"]],
    ["triceps-pushdown","Extensión de tríceps en polea",["tríceps polea"],"gym","isolation",["cable"],["gym"],["tríceps"],"Extensión con banda","Extensión unilateral",["assisted-dip","push-up"]],
    ["leg-press","Prensa de piernas",["prensa"],"gym","squat",["leg_press"],["gym"],["cuádriceps","glúteos"],"Prensa con rango corto","Prensa unilateral",["back-squat","tempo-squat"]],
    ["leg-curl","Curl femoral",["femoral"],"gym","isolation",["leg_curl"],["gym"],["isquiotibiales"],"Curl con rango corto","Curl unilateral",["slider-leg-curl","romanian-deadlift"]],
    ["tempo-squat","Sentadilla tempo",["sentadilla corporal"],"bodyweight","squat",[],["home","outdoor","gym"],["cuádriceps","glúteos"],"Sentarse y levantarse de una silla","Sentadilla con pausa",["back-squat","step-up"]],
    ["push-up","Flexión de brazos",["flexiones"],"bodyweight","push",[],["home","outdoor","gym"],["pecho","tríceps"],"Flexión inclinada","Flexión con pausa",["incline-push-up","bench-press"]],
    ["incline-push-up","Flexión inclinada",["flexión elevada"],"bodyweight","push",["bench_or_wall"],["home","outdoor","gym"],["pecho","tríceps"],"Flexión contra pared","Flexión en el suelo",["push-up","assisted-dip"]],
    ["band-row","Remo con banda",["remo invertido"],"bodyweight","pull",["resistance_band"],["home","outdoor","gym"],["espalda","bíceps"],"Remo con menor tensión","Remo invertido",["seated-cable-row","assisted-pull-up"]],
    ["glute-bridge","Puente de glúteo",["puente"],"bodyweight","bridge",[],["home","gym"],["glúteos","isquiotibiales"],"Puente con rango corto","Puente a una pierna",["barbell-hip-thrust","single-leg-glute-bridge"]],
    ["single-leg-glute-bridge","Puente de glúteo a una pierna",["puente unilateral"],"bodyweight","bridge",[],["home","gym"],["glúteos","isquiotibiales"],"Puente bilateral","Puente unilateral con pausa",["glute-bridge","barbell-hip-thrust"]],
    ["front-plank","Plancha frontal",["plancha"],"bodyweight","core",[],["home","gym"],["core"],"Plancha elevada","Plancha con mayor duración",["dead-bug","side-plank"]],
    ["side-plank","Plancha lateral",["plancha de lado"],"bodyweight","core",[],["home","gym"],["core","oblicuos"],"Plancha lateral con rodillas","Plancha lateral con pierna elevada",["front-plank","dead-bug"]],
    ["dead-bug","Dead bug",["insecto muerto"],"bodyweight","core",[],["home","gym"],["core"],"Mover solo brazos o piernas","Extender brazo y pierna opuestos",["front-plank","shoulder-tap-plank"]],
    ["pike-push-up","Pike push-up",["flexión pica"],"bodyweight","push",[],["home","gym"],["hombros","tríceps"],"Pike con manos elevadas","Pike con pies elevados",["overhead-press","incline-push-up"]],
    ["single-leg-rdl","Peso muerto a una pierna",["bisagra unilateral"],"bodyweight","hinge",[],["home","gym"],["isquiotibiales","glúteos"],"Bisagra asistida","Bisagra unilateral con carga",["romanian-deadlift","glute-bridge"]],
    ["assisted-pull-up","Dominada asistida",["dominada con banda"],"bodyweight","pull",["pullup_bar","resistance_band"],["home","outdoor","gym"],["espalda","bíceps"],"Jalón con banda","Dominada con menos asistencia",["lat-pulldown","band-row"]],
    ["shoulder-tap-plank","Plancha con toque de hombro",["toques de hombro"],"bodyweight","core",[],["home","gym"],["core","hombros"],"Plancha alta sin toques","Toques más lentos",["front-plank","dead-bug"]],
    ["step-up","Subida al banco",["step ups"],"bodyweight","lunge",["step_or_bench"],["home","outdoor","gym"],["cuádriceps","glúteos"],"Escalón bajo con apoyo","Escalón más alto o con carga",["walking-lunge","bulgarian-split-squat"]],
    ["slider-leg-curl","Curl femoral deslizante",["curl deslizante"],"bodyweight","hinge",["sliders_or_towel"],["home","gym"],["isquiotibiales","glúteos"],"Deslizar una pierna por vez","Curl completo con cadera elevada",["leg-curl","glute-bridge"]],
  ].map(row=>exercise({
    slug:row[0],name:row[1],aliases:row[2],discipline:row[3],pattern:row[4],
    equipment:row[5],places:row[6],muscles:row[7],regression:row[8],
    progression:row[9],substitutes:row[10],
  }));

  const endurance=[
    ["run-intervals","Intervalos de running","running","run","Series de carrera suave con más recuperación","Aumentar gradualmente la duración del bloque rápido",["run-easy","run-drills"]],
    ["run-easy","Running aeróbico fácil","running","run","Alternar caminar y correr","Aumentar tiempo manteniendo ritmo conversacional",["run-intervals","run-drills"]],
    ["run-drills","Técnica de carrera","running","run","Marcha técnica y progresivos cortos","Añadir repeticiones sin perder postura",["run-easy"]],
    ["cycle-intervals","Intervalos de cycling","cycling","cycle","Bloques cortos con resistencia moderada","Aumentar duración antes que resistencia",["cycle-endurance","cycle-cadence"]],
    ["cycle-endurance","Cycling aeróbico fácil","cycling","cycle","Sesión más corta y resistencia baja","Aumentar tiempo en zona cómoda",["cycle-intervals","cycle-cadence"]],
    ["cycle-cadence","Técnica y cadencia en bicicleta","cycling","cycle","Cadencia cómoda con bloques breves","Bloques más largos sin balancear el tronco",["cycle-endurance"]],
    ["swim-intervals","Intervalos de natación","swimming","swim","Bloques más cortos con pausa amplia","Aumentar distancia manteniendo técnica",["swim-endurance","swim-drills"]],
    ["swim-endurance","Natación aeróbica fácil","swimming","swim","Alternar largos suaves y pausas","Aumentar distancia sin perder alineación",["swim-intervals","swim-drills"]],
    ["swim-drills","Técnica de natación","swimming","swim","Un ejercicio técnico por bloque","Combinar ejercicios manteniendo respiración estable",["swim-endurance"]],
  ].map(row=>exercise({
    slug:row[0],name:row[1],aliases:[],discipline:row[2],pattern:row[3],
    equipment:row[2]==="cycling"?["bicycle"]:row[2]==="swimming"?["pool"]:[],
    places:row[2]==="swimming"?["pool"]:row[2]==="cycling"?["outdoor","gym"]:["outdoor"],
    muscles:row[2]==="swimming"?["cuerpo completo"]:["piernas","sistema cardiovascular"],
    regression:row[4],progression:row[5],substitutes:row[6],
  }));

  root.FITBUD_EXERCISES=strength.concat(endurance);
  root.FITBUD_WORKOUT_EXERCISES={
    gym:{
      fullA:["back-squat","bench-press","seated-cable-row","romanian-deadlift","dead-bug"],
      fullB:["barbell-hip-thrust","incline-dumbbell-press","lat-pulldown","bulgarian-split-squat","side-plank"],
      torsoA:["bench-press","seated-cable-row","overhead-press","lat-pulldown"],
      piernaA:["back-squat","romanian-deadlift","walking-lunge","standing-calf-raise"],
      torsoB:["incline-dumbbell-press","seated-cable-row","assisted-dip","biceps-curl","triceps-pushdown"],
      piernaB:["leg-press","barbell-hip-thrust","bulgarian-split-squat","leg-curl"],
    },
    bodyweight:{
      fullA:["tempo-squat","push-up","band-row","glute-bridge","front-plank"],
      fullB:["bulgarian-split-squat","pike-push-up","band-row","single-leg-rdl","side-plank"],
      torsoA:["push-up","band-row","pike-push-up","assisted-pull-up"],
      piernaA:["tempo-squat","walking-lunge","single-leg-glute-bridge","standing-calf-raise"],
      torsoB:["incline-push-up","band-row","assisted-dip","shoulder-tap-plank"],
      piernaB:["bulgarian-split-squat","single-leg-rdl","step-up","slider-leg-curl","dead-bug"],
    },
    running:{calidad:["run-intervals"],facil:["run-easy"],tecnica:["run-drills"]},
    cycling:{calidad:["cycle-intervals"],facil:["cycle-endurance"],tecnica:["cycle-cadence"]},
    swimming:{calidad:["swim-intervals"],facil:["swim-endurance"],tecnica:["swim-drills"]},
  };
})(typeof window!=="undefined"?window:globalThis);
